// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADhdeA-qHEz-6mef6TWZn6MaY9oE-MBHc',
    appId: '1:661736387117:web:cdda5bb5e456d702793ea4',
    messagingSenderId: '661736387117',
    projectId: 'forum-app-f60c9',
    authDomain: 'forum-app-f60c9.firebaseapp.com',
    storageBucket: 'forum-app-f60c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBifGzs-VmL0am1MJjYuTEmve8Qz4hFGDA',
    appId: '1:661736387117:android:240c313169a3e243793ea4',
    messagingSenderId: '661736387117',
    projectId: 'forum-app-f60c9',
    storageBucket: 'forum-app-f60c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWDGyuXsqPZ1tzNfKeFGwnJxMPPHlpNpg',
    appId: '1:661736387117:ios:7b354f6733426e3e793ea4',
    messagingSenderId: '661736387117',
    projectId: 'forum-app-f60c9',
    storageBucket: 'forum-app-f60c9.firebasestorage.app',
    iosBundleId: 'com.example.forumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWDGyuXsqPZ1tzNfKeFGwnJxMPPHlpNpg',
    appId: '1:661736387117:ios:7b354f6733426e3e793ea4',
    messagingSenderId: '661736387117',
    projectId: 'forum-app-f60c9',
    storageBucket: 'forum-app-f60c9.firebasestorage.app',
    iosBundleId: 'com.example.forumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADhdeA-qHEz-6mef6TWZn6MaY9oE-MBHc',
    appId: '1:661736387117:web:c0a3889cfea505af793ea4',
    messagingSenderId: '661736387117',
    projectId: 'forum-app-f60c9',
    authDomain: 'forum-app-f60c9.firebaseapp.com',
    storageBucket: 'forum-app-f60c9.firebasestorage.app',
  );
}
